giddy-dump:
  users:
    :columns:
    - id:
      :source: _id
      :type: TEXT
    - created_at:
      :source: createdAt
      :type: TIMESTAMP WITH TIME ZONE
    - updated_at:
      :source: updatedAt
      :type: TIMESTAMP WITH TIME ZONE
    - email:
      :source: email
      :type: TEXT
    - selected_shipping_state:
      :source: selectedShippingState
      :type: TEXT
    - selected_postal_code:
      :source: selectedPostalCode
      :type: TEXT
    - num_successful_orders:
      :source: numSuccessfulOrders
      :type: INTEGER
    - invite_code_used:
      :source: inviteCodeUsed
      :type: TEXT
    - generated_invite_code:
      :source: generatedInviteCode
      :type: TEXT
    - deleted:
      :source: deleted
      :type: BOOLEAN
    - lifetime_savings:
      :source: stats.lifetimeSavings
      :type: DOUBLE PRECISION
    - cart:
      :source: cart
      :type: TEXT
    - wishlist:
      :source: wishlist
      :type: TEXT
    - reward_amount:
      :source: loyalty.rewardAmount
      :type: DOUBLE PRECISION
    - business_account:
      :source: businessAccount
      :type: TEXT
    - is_commercial:
      :source: isCommercial
      :type: BOOLEAN
    - sailthru_sid:
      :source: sailthruSid
      :type: TEXT
    - client_view_type:
      :source: clientViewType
      :type: INTEGER
    - tier_locked:
      :source: tierLocked
      :type: BOOLEAN
    - tier:
      :source: tier
      :type: TEXT
    :meta:
      :table: users_temp_stg
  orders:
    :columns:
    - id:
      :source: _id
      :type: TEXT
    - gid:
      :source: gid
      :type: BIGINT
    - created_at:
      :source: createdAt
      :type: TIMESTAMP WITH TIME ZONE
    - updated_at:
      :source: updatedAt
      :type: TIMESTAMP WITH TIME ZONE
    - user:
      :source: user
      :type: TEXT
    - guestEmail:
      :source: guestEmail
      :type: TEXT
    - is_test_order:
      :source: isTestOrder
      :type: BOOLEAN
    - financial_status:
      :source: financialStatus
      :type: INTEGER
    - fulfillment_status:
      :source: fulfillmentStatus
      :type: INTEGER
    - current_express_order_status:
      :source: currentExpressOrderStatus
      :type: INTEGER
    - fulfillment_order_status:
      :source: fulfillmentOrderStatus
      :type: INTEGER
    - payment_method:
      :source: paymentMethod
      :type: INTEGER
    - business_account:
      :source: businessAccount
      :type: TEXT
    - fulfiller_order_id:
      :source: fulfillerOrderId
      :type: TEXT
    - warehouse:
      :source: warehouse
      :type: TEXT
    - fulfiller_type:
      :source: fulfillerType
      :type: INTEGER
    - shipping_address_first_name:
      :source: shippingAddress.firstName
      :type: TEXT
    - shipping_address_last_name:
      :source: shippingAddress.lastName
      :type: TEXT
    - shipping_address_address_line_1:
      :source: shippingAddress.addressLine1
      :type: TEXT
    - shipping_address_address_line_2:
      :source: shippingAddress.addressLine2
      :type: TEXT
    - shipping_address_city:
      :source: shippingAddress.city
      :type: TEXT
    - shipping_address_state:
      :source: shippingAddress.state
      :type: TEXT
    - shipping_address_postal_code:
      :source: shippingAddress.postalCode
      :type: TEXT
    - shipping_address_country:
      :source: shippingAddress.country
      :type: TEXT
    - shipping_address_is_commercial_address:
      :source: shippingAddress.isCommercialAddress
      :type: BOOLEAN
    - billing_info_address_first_name:
      :source: billingInfo.billingAddress.firstName
      :type: TEXT
    - billing_info_address_last_name:
      :source: billingInfo.billingAddress.lastName
      :type: TEXT
    - billing_info_address_address_line_1:
      :source: billingInfo.billingAddress.addressLine1
      :type: TEXT
    - billing_info_address_address_line_2:
      :source: billingInfo.billingAddress.addressLine2
      :type: TEXT
    - billing_info_address_city:
      :source: billingInfo.billingAddress.city
      :type: TEXT
    - billing_info_address_state:
      :source: billingInfo.billingAddress.state
      :type: TEXT
    - billing_info_address_postal_code:
      :source: billingInfo.billingAddress.postalCode
      :type: TEXT
    - billing_info_address_country:
      :source: billingInfo.billingAddress.country
      :type: TEXT
    - billing_info_card_expiration_date:
      :source: billingInfo.card.expirationDate
      :type: TEXT
    - billing_info_card_masked_number:
      :source: billingInfo.card.masked_Number
      :type: TEXT
    - billing_info_card_last4:
      :source: billingInfo.card.last4
      :type: TEXT
    - billing_info_card_cc_token:
      :source: billingInfo.card.ccToken
      :type: TEXT
    - billing_info_card_card_type:
      :source: billingInfo.card.cardType
      :type: TEXT
    - pricing_info_variants_subtotal_price:
      :source: pricingInfo.variantsSubtotalPrice
      :type: NUMERIC(20,6)
    - pricing_info_shipping_price:
      :source: pricingInfo.shippingPrice
      :type: NUMERIC(20,6)
    - pricing_info_tax_amount:
      :source: pricingInfo.taxAmount
      :type: NUMERIC(20,6)
    - pricing_info_promo_discount:
      :source: pricingInfo.promoDiscount
      :type: NUMERIC(20,6)
    - pricing_info_credit_deduction:
      :source: pricingInfo.creditDeduction
      :type: NUMERIC(20,6)
    - pricing_info_reward_deduction:
      :source: pricingInfo.rewardDeduction
      :type: NUMERIC(20,6)
    - pricing_info_total_price:
      :source: pricingInfo.totalPrice
      :type: NUMERIC(20,6)
    - pricing_info_total_price_before_deductions:
      :source: pricingInfo.totalPriceBeforeDeductions
      :type: NUMERIC(20,6)
    - shipping_price_config_low_price:
      :source: shippingPriceConfig.lowPrice
      :type: NUMERIC(20,6)
    - shipping_price_config_high_price:
      :source: shippingPriceConfig.highPrice
      :type: NUMERIC(20,6)
    - shipping_price_config_speed_type:
      :source: shippingPriceConfig.speedType
      :type: NUMERIC(20,6)
    - shipping_price_config_pricing_type:
      :source: shippingPriceConfig.pricingType
      :type: NUMERIC(20,6)
    - shipping_price_config_flat_type:
      :source: shippingPriceConfig.flatType
      :type: NUMERIC(20,6)
    - request_source_operating_system:
      :source: requestSource.operatingSystem
      :type: TEXT
    - request_source_operating_system_major_version:
      :source: requestSource.operatingSystemMajorVersion
      :type: TEXT
    - request_source_device:
      :source: requestSource.device
      :type: TEXT
    - platform:
      :source: platform
      :type: TEXT
    - invite_credit_amount:
      :source: inviteCreditAmount
      :type: NUMERIC(20,6)
    - promo_code_overage_credit_amount:
      :source: promoCodeOverageCreditAmount
      :type: NUMERIC(20,6)
    - promo_codes:
      :source: promoCodes
      :type: JSON
    - app_version:
      :source: appVersion
      :type: TEXT
    - braintree_zero_payment_info_text:
      :source: braintreeZeroPaymentInfo.infoText
      :type: TEXT
    - braintree_zero_payment_info_payment_provider_type:
      :source: braintreeZeroPaymentInfo.paymentProviderType
      :type: INTEGER
    - submitted_settlement_at:
      :source: submittedSettlementAt
      :type: TIMESTAMP WITH TIME ZONE
    - settlement_date:
      :source: settlementDate
      :type: TIMESTAMP WITH TIME ZONE
    - mosql_updated_at:
      :source: $timestamp
      :type: TIMESTAMP WITH TIME ZONE
    - potential_invite_credit_amount:
      :source: potentialInviteCreditAmount
      :type: NUMERIC(20,6)
    - refunds:
      :source: refunds
      :type: JSON
    - purchase_order_number:
      :source: purchaseOrderNumber
      :type: TEXT
    - order_item_delivery:
      :source: orderVariants.orderItemDelivery
      :type: TEXT[]
    :meta:
      :table: orders_temp_stg
